// This file is generated by Doubao 2.1 Turbo.
#include "configtool.hpp"
#include "resource.h"
#include <shlobj.h>
#include <uxtheme.h>
#include <string>
#pragma comment(lib, "uxtheme.lib")

using namespace std;
using namespace w32oop::util::str::converts;

extern HINSTANCE hInst;

// ===========================================================================
//  ConfigItemDef defaults  (values mirror MyProcControlLite_ServiceParameters)
// ===========================================================================
#define DefineParam(Name, Desc) { L ## #Name , Desc, MyProcControlLite_ServiceParameters().Name }
const MyProcControl_Lite::ConfigItemDef MyProcControl_Lite::ConfigTool::itemDefs[] = {
	DefineParam(FailOpen, L"Fail-Open"),
	DefineParam(ConsentTimeout, L"Timeout in seconds for consent dialogs before auto-deny. -1 means no timeout."),
	DefineParam(EnableAggressiveLauncher, L"Enable more aggressive launcher. If enabled, the launcher will be safer but "
		"some antimalware softwares may flag this product as malicious. Don't worry - there are no malware here."),
	DefineParam(NoConsentOnUnprivilegedSession, L"Block consent dialogs on unprivileged Windows session "
		"if request comes from services session (0)."),
};
#undef DefineParam
size_t MyProcControl_Lite::ConfigTool::ITEM_COUNT = std::size(MyProcControl_Lite::ConfigTool::itemDefs);

// ===========================================================================
//  std::any helpers  (templates + type dispatch; no any→RegistryValue wrap
//  — RegistryValue's ctor already accepts std::any&& directly)
// ===========================================================================
namespace {

// Read a REG_DWORD from the key and cast it to T.
// Generic so the caller decides the target C++ type (bool / DWORD / int / …).
template<typename T>
requires std::is_integral_v<T>
T read_dword_as(const RegistryKey& key, const wchar_t* name, T fallback) {
	return static_cast<T>(key.get_value_or<DWORD>(name, static_cast<DWORD>(fallback)));
}

// Render any supported config value as its display string.
// Supported types: bool, DWORD, ULONGLONG, wstring.
wstring any_to_display(const std::any& v) {
	if (!v.has_value()) return L"";
	if (v.type() == typeid(bool))
		return std::to_wstring(std::any_cast<bool>(v) ? 1 : 0);
	if (v.type() == typeid(DWORD))
		return std::to_wstring(std::any_cast<DWORD>(v));
	if (v.type() == typeid(ULONGLONG))
		return std::to_wstring(std::any_cast<ULONGLONG>(v));
	if (v.type() == typeid(wstring))
		return std::any_cast<wstring>(v);
	return L"<unsupported>";
}

// Read a registry value into std::any, using def's type as the target guide.
// bool/DWORD → REG_DWORD, ULONGLONG → REG_QWORD, wstring → REG_SZ.
std::any read_any_from_registry(const RegistryKey& key, const wchar_t* name, const std::any& def) {
	if (def.type() == typeid(bool))
		return read_dword_as<bool>(key, name, std::any_cast<bool>(def));
	if (def.type() == typeid(DWORD))
		return read_dword_as<DWORD>(key, name, std::any_cast<DWORD>(def));
	if (def.type() == typeid(ULONGLONG))
		return key.get_value_or<ULONGLONG>(name, std::any_cast<ULONGLONG>(def));
	if (def.type() == typeid(wstring))
		return key.get_value_or<wstring>(name, std::any_cast<wstring>(def));
	return def;
}

} // anonymous namespace

// ===========================================================================
//  ListView  — column / item helpers
// ===========================================================================
void MyProcControl_Lite::ListView::onCreated() {
	send(LVM_SETEXTENDEDLISTVIEWSTYLE,
		LVS_EX_FULLROWSELECT | LVS_EX_GRIDLINES | LVS_EX_DOUBLEBUFFER,
		LVS_EX_FULLROWSELECT | LVS_EX_GRIDLINES | LVS_EX_DOUBLEBUFFER);
	SetWindowTheme(hwnd, L"Explorer", nullptr);
}

void MyProcControl_Lite::ListView::setup_event_handlers() {
	WINDOW_EVENT_HANDLER_SUPER(BaseSystemWindow);
	WINDOW_add_notification_handler(NM_DBLCLK, handleDoubleClick);
	WINDOW_add_handler(WM_CONTEXTMENU, handleContextMenu);
}

void MyProcControl_Lite::ListView::handleDoubleClick(EventData& ev) {
	if (doubleClickHandler) doubleClickHandler(ev);
}

void MyProcControl_Lite::ListView::handleContextMenu(EventData& ev) {
	ev.preventDefault();
	POINT pt{};
	GetCursorPos(&pt);
	POINT clientPt = pt;
	ScreenToClient(hwnd, &clientPt);
	int item = hitTest(clientPt.x, clientPt.y);
	if (item >= 0) {
		LVITEMW lvItem{};
		lvItem.mask = LVIF_STATE;
		lvItem.state = LVIS_SELECTED | LVIS_FOCUSED;
		lvItem.stateMask = LVIS_SELECTED | LVIS_FOCUSED;
		send(LVM_SETITEMSTATE, item, (LPARAM)&lvItem);
		if (contextMenuHandler) contextMenuHandler(ev);
	}
}

void MyProcControl_Lite::ListView::addColumn(const std::wstring& text, int width, int fmt) {
	LVCOLUMNW col{};
	col.mask = LVCF_TEXT | LVCF_WIDTH | LVCF_FMT;
	col.fmt = fmt;
	col.cx = scaled(width);
	col.pszText = const_cast<LPWSTR>(text.c_str());
	send(LVM_INSERTCOLUMN, getColumnCount(), (LPARAM)&col);
}

void MyProcControl_Lite::ListView::setColumnWidth(int col, int width) {
	send(LVM_SETCOLUMNWIDTH, col, scaled(width));
}

int MyProcControl_Lite::ListView::getColumnCount() {
	HWND hHeader = (HWND)send(LVM_GETHEADER, 0, 0);
	if (!hHeader) return 0;
	return Header_GetItemCount(hHeader);
}

int MyProcControl_Lite::ListView::getItemCount() {
	return (int)send(LVM_GETITEMCOUNT, 0, 0);
}

int MyProcControl_Lite::ListView::addItem(const std::wstring& text) {
	LVITEMW item{};
	item.mask = LVIF_TEXT;
	item.iItem = getItemCount();
	item.pszText = const_cast<LPWSTR>(text.c_str());
	return (int)send(LVM_INSERTITEM, 0, (LPARAM)&item);
}

void MyProcControl_Lite::ListView::setItemText(int item, int subItem, const std::wstring& text) {
	LVITEMW lvItem{};
	lvItem.mask = LVIF_TEXT;
	lvItem.iItem = item;
	lvItem.iSubItem = subItem;
	lvItem.pszText = const_cast<LPWSTR>(text.c_str());
	send(LVM_SETITEMTEXT, item, (LPARAM)&lvItem);
}

std::wstring MyProcControl_Lite::ListView::getItemText(int item, int subItem) {
	wchar_t buf[1024] = {};
	LVITEMW lvItem{};
	lvItem.mask = LVIF_TEXT;
	lvItem.iItem = item;
	lvItem.iSubItem = subItem;
	lvItem.pszText = buf;
	lvItem.cchTextMax = 1024;
	send(LVM_GETITEMTEXT, item, (LPARAM)&lvItem);
	return std::wstring(buf);
}

int MyProcControl_Lite::ListView::getSelectedItem() {
	return (int)send(LVM_GETNEXTITEM, -1, LVNI_SELECTED);
}

void MyProcControl_Lite::ListView::deleteAllItems() {
	send(LVM_DELETEALLITEMS, 0, 0);
}

int MyProcControl_Lite::ListView::hitTest(int x, int y) {
	LVHITTESTINFO ht{};
	ht.pt.x = x;
	ht.pt.y = y;
	send(LVM_HITTEST, 0, (LPARAM)&ht);
	if (ht.flags & LVHT_ONITEM) return ht.iItem;
	return -1;
}

void MyProcControl_Lite::ListView::autoSizeLastColumn(int col0Width, int col1Width) {
	RECT rc = client_rect();
	int clientW = rc.right - rc.left;
	int lastW = clientW - col0Width - col1Width;
	if (lastW < 50) lastW = 50;
	setColumnWidth(0, col0Width);
	setColumnWidth(1, col1Width);
	setColumnWidth(2, lastW);
}

// ===========================================================================
//  ConfigTool
// ===========================================================================
MyProcControl_Lite::ConfigTool::ConfigTool(std::wstring name, bool withName)
	: Window(L"Config Tool - My Proc Control Lite", 680, 480, 0, 0, WS_OVERLAPPEDWINDOW),
	  svc(name), withName(withName) {}

HICON MyProcControl_Lite::ConfigTool::get_window_icon() {
	static HICON icon = LoadIconW(hInst, MAKEINTRESOURCEW(IDI_ICON_APP));
	return icon;
}

void MyProcControl_Lite::ConfigTool::setup_event_handlers() {
	addEventListener(0x0005, [this](EventData& data) { doLayout(); });;
}

void MyProcControl_Lite::ConfigTool::onCreated() {
	isAdmin = checkIsAdmin();

	// --- elevation banner (shown only when !isAdmin) ---
	elevateText.set_parent(this);
	elevateText.create(L"You need to elevate so that you can configure the service.",
		100, BANNER_HEIGHT, 0, 0, Static::STYLE | SS_CENTERIMAGE);
	elevateBtn.set_parent(this);
	elevateBtn.create(L"Elevate now", BTN_WIDTH, BANNER_HEIGHT, 0, 0);
	elevateBtn.onClick([this](EventData&) { elevateNow(true); });
	elevateText.backgroundColor(RgbColor("rgb(253,246,236)"));
	elevateText.color(RgbColor("#e6a23c"));

	// --- target row ---
	targetText.set_parent(this);
	targetText.create(L"Current target: " + svc, 100, ROW_HEIGHT, 0, 0, Static::STYLE | SS_CENTERIMAGE);
	changeBtn.set_parent(this);
	changeBtn.create(L"Change...", CHANGE_BTN_WIDTH, ROW_HEIGHT, 0, 0);
	changeBtn.onClick([this](EventData&) { if (!withName) changeTarget(); });
	if (withName) changeBtn.disable();

	// --- list view ---
	listView.set_parent(this);
	listView.create(L"", 100, 100, 0, 0);
	listView.addColumn(L"Name", COL_NAME_WIDTH);
	listView.addColumn(L"Value", COL_VALUE_WIDTH);
	listView.addColumn(L"Description", 100);
	listView.onDoubleClick([this](EventData&) { editSelectedItem(); });
	listView.onContextMenu([this](EventData&) { showContextMenu(); });

	// --- bottom buttons ---
	uninstallBtn.set_parent(this);
	uninstallBtn.create(L"Uninstall", BTN_WIDTH, BUTTON_HEIGHT, 0, 0);
	uninstallBtn.onClick([this](EventData&) { uninstallNow(); });

	configureBtn.set_parent(this);
	configureBtn.create(L"Configure Now", CONFIG_BTN_WIDTH, BUTTON_HEIGHT, 0, 0);
	configureBtn.onClick([this](EventData&) { configureNow(); });

	cancelBtn.set_parent(this);
	cancelBtn.create(L"Cancel", BTN_WIDTH, BUTTON_HEIGHT, 0, 0);
	cancelBtn.onClick([this](EventData&) { close(); });

	// --- state ---
	checkServiceStatus();
	loadConfigFromRegistry();
	populateListView();
	updateButtonStates();

	doLayout();
}

void MyProcControl_Lite::ConfigTool::onDestroy() {}

// ---------------------------------------------------------------------------
//  layout
// ---------------------------------------------------------------------------
void MyProcControl_Lite::ConfigTool::doLayout() {
	if (!listView.created()) return;

	RECT rc = client_rect();
	int W = rc.right - rc.left;
	int H = rc.bottom - rc.top;
	int top = MARGIN;
	
	// elevation banner (conditional)
	if (!isAdmin) {
		elevateText.show();
		elevateBtn.show();
		elevateText.resize(MARGIN, top,
			W - MARGIN * 2 - BTN_WIDTH - GAP, BANNER_HEIGHT);
		elevateBtn.resize(W - MARGIN - BTN_WIDTH, top,
			BTN_WIDTH, BANNER_HEIGHT);
		top += BANNER_HEIGHT + GAP;
	} else {
		elevateText.hide();
		elevateBtn.hide();
	}

	// target row
	targetText.resize(MARGIN, top,
		W - MARGIN * 2 - CHANGE_BTN_WIDTH - GAP, ROW_HEIGHT);
	changeBtn.resize(W - MARGIN - CHANGE_BTN_WIDTH, top,
		CHANGE_BTN_WIDTH, ROW_HEIGHT);
	top += ROW_HEIGHT + GAP;

	// list view (fills remaining space above button row)
	int bottomY = H - MARGIN - BUTTON_HEIGHT;
	int listH = bottomY - GAP - top;
	if (listH < 50) listH = 50;
	listView.resize(MARGIN, top, W - MARGIN * 2, listH);
	listView.autoSizeLastColumn(COL_NAME_WIDTH, COL_VALUE_WIDTH);

	// bottom buttons — right aligned: Uninstall | Configure Now | Cancel
	int cancelX    = W - MARGIN - BTN_WIDTH;
	int configureX = cancelX - GAP - CONFIG_BTN_WIDTH;
	int uninstallX = configureX - GAP - BTN_WIDTH;
	cancelBtn.resize(cancelX, bottomY, BTN_WIDTH, BUTTON_HEIGHT);
	configureBtn.resize(configureX, bottomY, CONFIG_BTN_WIDTH, BUTTON_HEIGHT);
	uninstallBtn.resize(uninstallX, bottomY, BTN_WIDTH, BUTTON_HEIGHT);
}

// ---------------------------------------------------------------------------
//  state helpers
// ---------------------------------------------------------------------------
bool MyProcControl_Lite::ConfigTool::checkIsAdmin() {
	return IsUserAnAdmin() != FALSE;
}

void MyProcControl_Lite::ConfigTool::checkServiceStatus() {
	serviceInstalled = false;
	// read-only SCM access — works for standard users.
	// Use default-ctor + assign because w32BaseHandle's value ctor throws on NULL.
	w32ServiceHandle scm;
	scm = OpenSCManagerW(nullptr, nullptr, SC_MANAGER_CONNECT);
	if (!scm.is_valid()) return;
	w32ServiceHandle hService;
	hService = OpenServiceW(scm, svc.c_str(), SERVICE_QUERY_STATUS);
	serviceInstalled = hService.is_valid();
}

void MyProcControl_Lite::ConfigTool::loadConfigFromRegistry() {
	itemValues.assign(ITEM_COUNT, std::any{});
	for (size_t i = 0; i < ITEM_COUNT; ++i)
		itemValues[i] = itemDefs[i].defaultValue;

	if (!serviceInstalled) return;
	try {
		RegistryKey params(HKEY_LOCAL_MACHINE,
			L"SYSTEM\\CurrentControlSet\\Services\\" + svc + L"\\Parameters", KEY_READ);
		for (size_t i = 0; i < ITEM_COUNT; ++i)
			itemValues[i] = read_any_from_registry(params, itemDefs[i].name, itemDefs[i].defaultValue);
	} catch (...) {
		// key absent or unreadable — defaults already applied
	}
}

void MyProcControl_Lite::ConfigTool::populateListView() {
	listView.deleteAllItems();
	for (size_t i = 0; i < ITEM_COUNT; ++i) {
		int idx = listView.addItem(itemDefs[i].name);
		listView.setItemText(idx, 1, any_to_display(itemValues[i]));
		listView.setItemText(idx, 2, itemDefs[i].description);
	}
}

void MyProcControl_Lite::ConfigTool::updateButtonStates() {
	if (!serviceInstalled) {
		uninstallBtn.disable();
		configureBtn.text(L"Install && Configure");
	} else {
		uninstallBtn.enable();
		configureBtn.text(L"Configure Now");
	}
	if (!isAdmin) {
		uninstallBtn.disable();
		configureBtn.disable();
	}
	targetText.color(serviceInstalled ? RgbColor("#080") : RgbColor("#f00"));
}

// ---------------------------------------------------------------------------
//  editing
// ---------------------------------------------------------------------------
void MyProcControl_Lite::ConfigTool::editSelectedItem() {
	if (!isAdmin) return;
	int idx = listView.getSelectedItem();
	if (idx < 0 || idx >= (int)ITEM_COUNT) return;

	InputDialog dlg(L"Edit Value", 420);
	dlg.create();
	dlg.setButtonsText(L"OK", L"Cancel");
	wstring prompt = L"Enter new value for " + wstring(itemDefs[idx].name) + L":";

	const std::any& cur = itemValues[idx];
	bool accepted = false;

	// Dispatch on the real C++ type: bool, DWORD, ULONGLONG, wstring.
	if (cur.type() == typeid(bool)) {
		auto r = dlg.getInput<int>(prompt, std::any_cast<bool>(cur) ? 1 : 0);
		if (r.has_value()) { itemValues[idx] = (r.value() != 0); accepted = true; }
	} else if (cur.type() == typeid(DWORD)) {
		auto r = dlg.getInput<DWORD>(prompt, std::any_cast<DWORD>(cur));
		if (r.has_value()) { itemValues[idx] = r.value(); accepted = true; }
	} else if (cur.type() == typeid(ULONGLONG)) {
		auto r = dlg.getInput<unsigned long long>(prompt, std::any_cast<ULONGLONG>(cur));
		if (r.has_value()) { itemValues[idx] = (ULONGLONG)r.value(); accepted = true; }
	} else if (cur.type() == typeid(wstring)) {
		auto r = dlg.getInput<wstring>(prompt, std::any_cast<wstring>(cur));
		if (r.has_value()) { itemValues[idx] = r.value(); accepted = true; }
	}

	if (!accepted) return;
	listView.setItemText(idx, 1, any_to_display(itemValues[idx]));
}

void MyProcControl_Lite::ConfigTool::resetSelectedItem() {
	int idx = listView.getSelectedItem();
	if (idx < 0 || idx >= (int)ITEM_COUNT) return;
	itemValues[idx] = itemDefs[idx].defaultValue;   // copy the typed default
	listView.setItemText(idx, 1, any_to_display(itemValues[idx]));
}

void MyProcControl_Lite::ConfigTool::showContextMenu() {
	Menu menu({
		MenuItem(L"&Edit...", 1),
		MenuItem::separator(),
		MenuItem(L"&Reset", 2),
	});
	if (!isAdmin) for (auto& i : menu.get_children()) if (i.is_string()) i.disable();
	int ret = menu.pop(this);
	if (ret == 1)      editSelectedItem();
	else if (ret == 2) resetSelectedItem();
}

// ---------------------------------------------------------------------------
//  button actions
// ---------------------------------------------------------------------------
void MyProcControl_Lite::ConfigTool::elevateNow(bool skipConfirm) {
setup_askprivilege:
	if (!skipConfirm) {
		int btn{};
		TaskDialog(hwnd, hInst, L"MyProcControl (Lite) Setup & Configure",
			L"Administrators privilege is required to configure the product.",
			L"Press Yes to continue.",
			TDCBF_YES_BUTTON | TDCBF_CANCEL_BUTTON,
			TD_SHIELD_ICON,
			&btn
		);
		if (btn != IDYES) return;
	}
	SHELLEXECUTEINFOW sei{};
	sei.cbSize = sizeof(sei);
	sei.fMask = SEE_MASK_NOCLOSEPROCESS;
	sei.lpVerb = L"runas";
	sei.nShow = SW_SHOW;
	sei.hwnd = hwnd;
	auto program = make_unique<WCHAR[]>(32768);
	GetModuleFileNameW(NULL, program.get(), 32768);
	sei.lpFile = program.get();
	wstring params = L"--type=config --name=\"" + svc + L"\"";
	sei.lpParameters = params.c_str();
	if (!ShellExecuteExW(&sei)) if (!skipConfirm) goto setup_askprivilege;
	if (!sei.hProcess) return;
	hide();
	WaitForSingleObject(sei.hProcess, INFINITE);
	DWORD exitCode{};
	GetExitCodeProcess(sei.hProcess, &exitCode);
	CloseHandle(sei.hProcess);
	PostQuitMessage( exitCode );
	close();
}

void MyProcControl_Lite::ConfigTool::changeTarget() {
	InputDialog dlg(L"Change Target Service", 420);
	dlg.create();
	dlg.setButtonsText(L"OK", L"Cancel");
	auto result = dlg.getInput<wstring>(L"Enter the service name:", svc);
	if (!result.has_value() || result.value().empty()) return;

	svc = result.value();
	targetText.text(L"Current target: " + svc);

	checkServiceStatus();
	loadConfigFromRegistry();
	populateListView();
	updateButtonStates();

	doLayout();
}

void MyProcControl_Lite::ConfigTool::configureNow() {
	if (!isAdmin) return;

	// fresh install: run setup --action=install first
	if (!serviceInstalled) {
		int exitCode = runSetupProcess(L"install");
		if (exitCode != 0) return;   // setup showed its own error dialog
		checkServiceStatus();          // should now report installed
		close();
		return;
	}

	// write parameters to registry (shared flow for both fresh & existing)
	try {
		RegistryKey serviceKey(HKEY_LOCAL_MACHINE,
			L"SYSTEM\\CurrentControlSet\\Services\\" + svc, KEY_WRITE);
		RegistryKey params = serviceKey.create(L"Parameters", KEY_WRITE);
		for (size_t i = 0; i < ITEM_COUNT; ++i) {
			const std::any& v = itemValues[i];
			// Only four types: bool→REG_DWORD, DWORD→REG_DWORD,
			// ULONGLONG→REG_QWORD (64-bit, no truncation), wstring→REG_SZ.
			if (v.type() == typeid(bool))
				params.set(itemDefs[i].name, RegistryValue((DWORD)(std::any_cast<bool>(v) ? 1 : 0), REG_DWORD));
			else if (v.type() == typeid(DWORD))
				params.set(itemDefs[i].name, RegistryValue(std::any_cast<DWORD>(v), REG_DWORD));
			else if (v.type() == typeid(ULONGLONG))
				params.set(itemDefs[i].name, RegistryValue(std::any_cast<ULONGLONG>(v), REG_QWORD));
			else if (v.type() == typeid(wstring))
				params.set(itemDefs[i].name, RegistryValue(std::any_cast<wstring>(v), REG_SZ));
		}
	} catch (const std::exception& e) {
		MessageBoxW(hwnd,
			(wstring(L"Failed to write registry parameters:\n") + str_wstr(e.what())).c_str(),
			L"Error", MB_ICONERROR);
		return;
	}

	if (MessageBoxW(hwnd, L"Configuration has been saved successfully!\nYou will need to restart the service to apply them!\n"
		L"Do you want to restart now?",
		L"Success", MB_OKCANCEL | MB_ICONINFORMATION) == IDOK) {
		hide();
		ServiceManager scm;
		auto sc = scm.get(this->svc);
		sc.stop();
		Sleep(3000);
		sc.start();
	}
	updateButtonStates();
	close();
}

void MyProcControl_Lite::ConfigTool::uninstallNow() {
	if (!isAdmin || !serviceInstalled) return;
	runSetupProcess(L"uninstall");
	checkServiceStatus();
	loadConfigFromRegistry();
	populateListView();
	updateButtonStates();
	close();
}

int MyProcControl_Lite::ConfigTool::runSetupProcess(const std::wstring& action) {
	wchar_t program[MAX_PATH] = {};
	GetModuleFileNameW(NULL, program, MAX_PATH);

	hide();
	//w32oop::util::RAIIHelper _([this] {show();});

	wstring cmdLine = L"\"" + wstring(program) +
		L"\" --type=setup --name=\"" + svc + L"\" --interactive --action=" + action;

	STARTUPINFOW si{ sizeof(si) };
	PROCESS_INFORMATION pi{};
	if (!CreateProcessW(NULL, cmdLine.data(), NULL, NULL, FALSE, 0, NULL, NULL, &si, &pi)) {
		DWORD err = GetLastError();
		MessageBoxW(hwnd,
			(wstring(L"Failed to start setup process: ") + ErrorChecker(err).message()).c_str(),
			L"Error", MB_ICONERROR);
		return (int)err;
	}
	CloseHandle(pi.hThread);
	WaitForSingleObject(pi.hProcess, INFINITE);
	DWORD exitCode = 0;
	GetExitCodeProcess(pi.hProcess, &exitCode);
	CloseHandle(pi.hProcess);
	return (int)exitCode;
}
