#pragma once
// This file is generated by Doubao 2.1 Turbo.
#include "targetver.h"
#include <w32use.hpp>
#include "srvconfig.h"
#include <vector>
#include <any>

namespace MyProcControl_Lite {

// ---------------------------------------------------------------------------
// ListView : a BaseSystemWindow-based wrapper around the Win32 SysListView32
// control.  We wrap it (rather than mixing vanilla Win32 with w32oop) so that
// DPI virtualisation, font propagation and the framework event router all stay
// consistent.
// ---------------------------------------------------------------------------
class ListView : public BaseSystemWindow {
public:
	static constexpr LONG STYLE =
		WS_CHILD | WS_VISIBLE | LVS_REPORT | LVS_SINGLESEL |
		LVS_SHOWSELALWAYS | WS_TABSTOP | WS_BORDER;

	ListView(HWND parent = nullptr, int width = 0, int height = 0,
		int x = 0, int y = 0, LONG style = STYLE)
		: BaseSystemWindow(parent, L"", width, height, x, y, style) {}

	// --- column management ------------------------------------------------
	void addColumn(const std::wstring& text, int width, int fmt = LVCFMT_LEFT);
	void setColumnWidth(int col, int width);
	int  getColumnCount();

	// --- item management --------------------------------------------------
	int  getItemCount();
	int  addItem(const std::wstring& text);
	void setItemText(int item, int subItem, const std::wstring& text);
	std::wstring getItemText(int item, int subItem);
	int  getSelectedItem();
	void deleteAllItems();

	// --- hit testing ------------------------------------------------------
	//  x,y are client coordinates (physical pixels).  Returns item index
	//  or -1 when the point is not on an item.
	int  hitTest(int x, int y);

	//  Make the last column fill the remaining client width.  col0Width
	//  and col1Width are the fixed logical widths of the first two columns.
	void autoSizeLastColumn(int col0Width, int col1Width);

	// --- event callbacks --------------------------------------------------
	void onDoubleClick(CEventHandler handler) { doubleClickHandler = handler; }
	void onContextMenu(CEventHandler handler) { contextMenuHandler = handler; }

protected:
	const std::wstring get_class_name() const override { return WC_LISTVIEWW; }
	void onCreated() override;
	void setup_event_handlers() override;

private:
	CEventHandler doubleClickHandler;
	CEventHandler contextMenuHandler;
	void handleDoubleClick(EventData& ev);
	void handleContextMenu(EventData& ev);
};

// ---------------------------------------------------------------------------
// ConfigItemDef : static description of one configurable parameter.
// Default values come from MyProcControlLite_ServiceParameters (srvconfig.h).
// ---------------------------------------------------------------------------
struct ConfigItemDef {
	const wchar_t* name;
	const wchar_t* description;
	std::any       defaultValue;
};

// ---------------------------------------------------------------------------
// ConfigTool : the main configuration dialog.
// ---------------------------------------------------------------------------
class ConfigTool : public Window {
public:
	ConfigTool(std::wstring name, bool withName);

protected:
	std::wstring svc;
	bool withName = false;
	bool         isAdmin          = false;
	bool         serviceInstalled = false;

	// --- child controls ---------------------------------------------------
	StaticEx elevateText;
	Button   elevateBtn;
	StaticEx targetText;
	Button   changeBtn;
	ListView listView;
	Button   uninstallBtn;
	Button   configureBtn;
	Button   cancelBtn;

	// --- config data ------------------------------------------------------
	static const ConfigItemDef itemDefs[];
	std::vector<std::any>      itemValues;   // in-memory working values
	static size_t ITEM_COUNT;

	// --- layout constants -------
	static constexpr int MARGIN            = 10;
	static constexpr int GAP               = 8;
	static constexpr int ROW_HEIGHT        = 28;
	static constexpr int BANNER_HEIGHT     = 32;
	static constexpr int BUTTON_HEIGHT     = 28;
	static constexpr int BTN_WIDTH         = 100;
	static constexpr int CONFIG_BTN_WIDTH  = 160;
	static constexpr int CHANGE_BTN_WIDTH  = 80;
	static constexpr int COL_NAME_WIDTH    = 200;
	static constexpr int COL_VALUE_WIDTH   = 100;

	COLORREF get_window_background_color() override { return RGB(0xf0, 0xf0, 0xf0); }
	HICON    get_window_icon() override;

	void setup_event_handlers() override;
	void onCreated() override;
	void onDestroy() override;

	void doLayout();

	// --- helpers ----------------------------------------------------------
	void checkServiceStatus();
	void loadConfigFromRegistry();
	void populateListView();
	void updateButtonStates();
	void editSelectedItem();
	void resetSelectedItem();
	void showContextMenu();
	void elevateNow(bool skipConfirm = false);
	void changeTarget();
	void configureNow();
	void uninstallNow();
	int  runSetupProcess(const std::wstring& action, PCWSTR app = NULL);
	static bool checkIsAdmin();
};

} // namespace MyProcControl_Lite
