[
	uuid(090AA68A-5F96-49E7-ADDB-3D09534833ED),
	version(1.0)
]
interface IServiceRpc
{
	int MyProcControlLite_LaunchWithControl([in, string] const wchar_t* application, [in, string] const wchar_t* cmdline, [out] int* bSuccess, [out] unsigned long* error);

	int MyProcControlLite_RequestAddControl([in] unsigned long dwProcessId, [out] unsigned long* error);

	int MyProcControlLite_Consent_CreateProcess([in, string] const wchar_t* application, [in, string] const wchar_t* cmdline, [in] int inherithandles, [in] unsigned long flags, [in, string] const wchar_t* cd, [in] unsigned long sisize, [out] unsigned long* custom_err_code);
}
